// File: pubspec.yaml
name: blocy
description: CLI tool to create Flutter apps with BLoC and clean architecture.
homepage: https://github.com/joysarkar18/blocy
repository: https://github.com/joysarkar18/blocy
version: 1.0.9
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  process_run: ^1.2.4
  ansicolor: ^2.0.1

executables:
  blocy: blocy
