// File: pubspec.yaml
name: blocy
description: A CLI tool for setting up Flutter projects with BLoC architecture
homepage: https://github.com/yourusername/your-package
repository: https://github.com/yourusername/your-package
version: 1.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  process_run: ^1.2.4
  ansicolor: ^2.0.1

executables:
  blocx: blocx
